### ISSUE TITLE
Container di supporto bag<T>

### ISSUE THREAD

**Issue by MatteoPecchie** [PEL-unive/progetto-23-24#1]
Per quanto riguarda il container di supporto bag<<T>> non ho capito bene a cosa serva. Capisco che esso mantenga l'insieme dei nodi figli ordinati per etichetta crescente, ma con che logica va sviluppato?

**Comment by nicolaprezza** [comment]
Con la logica che ritenete opportuna per risolvere l'esercizio. Siete liberi di scrivere quello che volete in bag.hpp. Suggerisco di iniziare a scrivere trie.cpp e, in base alle operazioni che vi servono sulla bag di figli, implementare successivamente bag.hpp.
