### ISSUE TITLE
Utilizzo di sorgente visto a lezione

### ISSUE THREAD

**Issue by kirpachov** [PEL-unive/progetto-23-24#10]
Salve buongiorno.
Apro questa issue per chiedere se è lecito utilizzare nel progetto codice scritto a lezione.
In particolare, vorrei implementare `bag<T>` con le liste ed utilizzare il codice scritto a lezione con il professor Pibiri, quello disponibile su moodle al seguente link:

[https://moodle.unive.it/mod/resource/view.php?id=808305](https://moodle.unive.it/mod/resource/view.php?id=808305)

Grazie
Oleksandr Kirpachov

**Comment by jermp** [comment]
Ciao,
sì puoi prendere spunto da quel codice e modificarlo per le esigenze di questo progetto.
