### ISSUE TITLE
Metodo add_child

### ISSUE THREAD

**Issue by PraiseTheSunOrDie** [PEL-unive/progetto-23-24#11]
Vorrei chiedere un chiarimento a proposito del metodo `add_child` del trie.

Dopo aver utilizzato:

`father.add_child(child);`

ci si aspetta che l'albero aggiunto al padre sia esattamente l'oggetto `child` dichiarato in precedenza, e che quindi le modifiche fatte successivamente ad esso come ad esempio
```
father.add_child(child);
int new_label = 4;
child.set_label(&new_label);
```
siano anche valide all'interno dell'oggetto aggiunto nel container `bag<T>` dell'oggetto padre?

Perché se così fosse, e se il nodo figlio venisse dichiarato in un altro scope rispetto al nodo padre, quando lo scope dovesse terminare, per caso verrebbe anche chiamato il distruttore di `child`? Se `child` dovesse venire distrutto, in `bag<T>` resterebbe un puntatore invalido.

**Comment by nicolaprezza** [comment]
Buongiorno, 

I trie contengono una `bag<trie<T>>`, non una `bag<trie<T>&>` (né `bag<trie<T>*>`) quindi `add_child()` non può fare altro che eseguire una deep-copy (copia per valore) dell'argomento. 

saluti, 
Nicola
