### ISSUE TITLE
problemi con get_children

### ISSUE THREAD

**Issue by RicuxUni** [PEL-unive/progetto-23-24#12]
Buonasera,
ho un problema con get_children
se lo metto nel file trie.cpp in questo modo 

```
template <typename T>
bag<trie<T>> const& trie<T>::get_children() const
	.....
}
```

ottengo l'errore 

`[Error] no declaration matches 'const bag<trie<T> >& trie<T>::get_children() const'`

se lo metto temporaneamente in coda a trie.hpp compila senza problemi.

grazie per l'attenzione

**Comment by jermp** [comment]
Errori di compilazione di questo tipo significano che la forma del metodo in `trie.hpp` non combacia con la firma dell'implementazione fornita in `trie.cpp`. Controlla meglio.
