### ISSUE TITLE
label del trie puntatore: copiare o non copiare?

### ISSUE THREAD

**Issue by kirpachov** [PEL-unive/progetto-23-24#13]
Salve buongiorno scrivo per un dubbio riguardo al metodo `set_label(T*)` di trie.
Sembra che quel puntatore debba essere salvato dentro l'oggetto.
Ma allora come facciamo a fare la copia senza andare in segfault?
Se copio un oggetto `trie<T>` con `m_l = <altro_trie>.m_l` avrò un segfault nel momento in cui dealloco il secondo trie.

Bisogna copiare l'oggetto puntato da T, e far puntare m_l ad una copia?
È quindi corretto questo comportamento:
```cpp
trie<char> t;
char ch = 'a';
t.set_label(&ch);
ch = 'b' // la label di t non verrà aggiornata.
```

Temo di non essere stato chiaro, se così fosse fatemi sapere che cerco di parafrasare

Grazie
Oleksandr Kirpachov

**Comment by jermp** [comment]
Ciao,
credo che tu abbia capito bene: il metodo accetta un puntatore ad una label ma dovrà farsi una copia privata della label puntata (che quindi poi il trie dovrà opportunamente de-allocare).

(D'altronde, il fatto che il metodo accetti un puntatore a label non implica automaticamente che il metodo si debba copiare il puntatore e basta.)

Fammi sapere se hai altri dubbi. Buon lavoro!

-Giulio

**Comment by kirpachov** [comment]
Perfetto, grazie

Oleksandr Kirpachov
