### ISSUE TITLE
<Chiarimento Progetto >

### ISSUE THREAD

**Issue by HR18HR** [PEL-unive/progetto-23-24#14]
Salve a tutti ,
Qualcuno potrebbe spiegarmi bene il progetto, perché non riesco a capire bene cosa bisogna fare ..
Scusate ma sono nuovo in questo mondo 😔
Grazie ``

**Comment by jermp** [comment]
Una buona idea è quella di leggere la specifica del progetto che spiega chiaramente cosa bisogna fare.
Devi implementare un container come visto a lezione per i contenitori map, list, json, etc.
Se hai bisogno di chiarimenti specifici, siamo a disposizione.

**Comment by HR18HR** [comment]
Grazie , ho letto le specifiche attentamente ma non ho capito se bisogna fare un container che fa il parsing di un file o bisogna costruire un albero con dati all’interno . Questa parte non mi è chiara 
Grazie ancora

**Comment by jermp** [comment]
Devi fare entrambe le cose. Il parser legge i dati da un file e li salva dentro il contenitore `trie`.

**Comment by HR18HR** [comment]
Ahn ok perfetto .Il contenitore viene modellato come un albero..
