### ISSUE TITLE
Iteratori per container bag

### ISSUE THREAD

**Issue by derenda-stud** [PEL-unive/progetto-23-24#15]
Ho notato che nel file `test_copy_move` della correzione parziale sono presenti chiamate alle funzioni `begin` ed `end` per costruire degli iteratori, che però fanno riferimento al container `bag`.

Mi chiedevo quindi: è necessario implementare anche questi due metodi nella bag oltre a quelli menzionati nel file di intestazione trie?

**Comment by jermp** [comment]
Gli iteratori su bag servono per implementare correttamente operator== di trie. Quindi, sì, bisogna implementarli. Infatti, quando ho presentato il progetto in classe, avevo esplicitamente suggerito di prendere spunto dal container list visto a lezione per implementare bag.
