### ISSUE TITLE
Output su ostream

### ISSUE THREAD

**Issue by H3r0F1r3** [PEL-unive/progetto-23-24#16]
Salve, vorrei chiedere un veloce chiarimento sul formato dell'output,

deve essere

1. {(<compilers,g++>,2.8), (<compilers,javac>,3.1), (<languages,c++>,1.1), (<languages,java>,0.5)}

oppure deve essere uguale all'input?

2. children = {
        compilers children = { g++ 2.8 children = {}, javac 3.1 children = {} },
	languages children = { c++ 1.1 children = {}, java 0.5 children = {} }
}

Grazie in anticipo

**Comment by nicolaprezza** [comment]
spazi/newline/tabs non fanno alcuna differenza, come specificato nella descrizione del progetto. Puoi decidere di stamparli sull'ostream oppure no.

**Comment by kirpachov** [comment]
Salve scusate se mi intrometto ma ho lo stesso dubbio.
Credo la domanda fosse: 
quando viene chiamato il metodo <<, come in quest caso:
`std::cout << my_trie`

Deve printare l'albero nello stesso formato in cui l'abbiamo letto, oppure nell'altro formato?


```
# Formato input
children = {
compilers children = { g++ 2.8 children = {}, javac 3.1 children = {} },
languages children = { c++ 1.1 children = {}, java 0.5 children = {} }
}
```

```
# "Altro" formato
{(<compilers,g++>,2.8), (<compilers,javac>,3.1), (<languages,c++>,1.1), (<languages,java>,0.5)}
```

Quindi, leggendo l'albero seguente e printandolo su standard output, dovremmo vedere:
```
trie<char> t;
std::cin >> t;
std::cout << t;

# A questo punto standard output cosa contiene?
# Un formato identico a quello di input oppure il formato "{(<compilers,g++>,2.8), (<compilers,javac>,3.1), (<languages,c++>,1.1), (<languages,java>,0.5)}" ?
```

**Comment by nicolaprezza** [comment]
Attenzione perchè quello che chiami "altro formato" non è un formato di file! è notazione matematica standard per indicare insiemi di coppie. Il formato associato a trie< T > è quello che chiami "formato di input".

**Comment by jermp** [comment]
Ovviamente il risultato di `operator<<` deve essere un formato trie **valido**. Questo significa che deve essere "parsabile" in un trie.

Ad esempio:

    trie<char> t;
    /* (code that fills t) */
    
    std::ofstream out("test.tr");
    out << t;
    out.close();
    
    trie<char> another;
    std::ifstream in("test.tr");
    in >> another;
    in.close();
    
    assert(t == another);


Quindi deve necessariamente contenere la stringa `children`, etc., ma eventuali caratteri whitespace possono essere ignorati perchè il parsing non deve considerarli.
