### ISSUE TITLE
whitespaces tra le keywords

### ISSUE THREAD

**Issue by kirpachov** [PEL-unive/progetto-23-24#17]
Salve buongiorno.
Apro questa issue per un breve chiarimento riguardo a dove possono o devono essere presenti whitespaces, in particolare intorno alla keyword 'children'.
Secondo quello che ho fatto fin'ora, la leaf deve avere il seguente pattern:

```

<label><one_or_more_whitespaces><weight><one_or_more_whitespaces>children<zero_or_more_whitespaces>=<zero_or_more_whitespaces>{<zero_or_more_whitespaces>}
```

Leaf valide:
```
a 1 children = {}
a 1 children = { }
a 1 children ={}
a 1 children={}
a 1 children={ }
```

Leaf invalide
```
a1 children = {}
a 1children = {}
a1children = {}
a1children = {}
```

Mi potreste confermare se il pattern da me descritto è corretto, o altrimenti indicarmi dove sbaglio?

Grazie
Oleksandr Kirpachov

**Comment by jermp** [comment]
Sì, giusto. Etichette e pesi devono essere necessariamente separati da almeno uno spazio, altrimenti per il parser sono indistinguibili e il formato di file non è corretto.

**Comment by kirpachov** [comment]
Perfetto, grazie!
