### ISSUE TITLE
Dubbio su path_compress()

### ISSUE THREAD

**Issue by Brugno04** [PEL-unive/progetto-23-24#18]
`children = {
    1 children = {
        9 16.1 children = {}
    }
}`

Salve, se io avessi questo trie di input per la funzione path_compress, quale dei due seguenti output è quello corretto? Ovvero, è corretto fare la compressione pure sulla radice, perdendo così il valore della label, oppure no?

1. `16.1 children = {}`
2. `children = { 10 16.1 children = {} }`

**Comment by jermp** [comment]
Ciao,
l'output 2 è quello corretto perchè la label della radice è nullptr e operator+ tra il tipo T e *nullptr non è definito.
Questo sarebbe piegato nella specifica con la frase "... (e dal loro arco entrante e unico arco uscente)".
Quindi, dato che la radice non ha nessun arco entrante, il trie `children = { 10 16.1 children = {} }` risulta già compresso.
