### ISSUE TITLE
Significato "maggior numero di elementi" nel Prefix Search

### ISSUE THREAD

**Issue by mattiacerutti** [PEL-unive/progetto-23-24#19]
Buongiorno, avrei bisogno di un chiarimento su come opera `operator[]`: 

Quando si dice che bisogna seguire il maggior numero di elementi di `s`, vuol dire che si possono ignorare certi percorsi rispetto ad altri se quest'ultimi portano ad arrivare ad una "maggiore profondità" nell'albero? Mi spiego meglio:

![image](https://github.com/PEL-unive/progetto-23-24/assets/71315146/73d87001-e0ca-4aea-b713-fcf71c8dd58e)

Nella seguente immagine, il vettore `s = {a, b, c}`, cosa ritornerà?
1. Il nodo con peso 3.1, in quanto scorrendo l'array troviamo che `s[0]` esiste, lo seguiamo, per poi doverci fermare in quanto non si può più proseguire
2. Il nodo in rosso, in quanto nonostante `s[0]` sia un percorso adatto, ci fa andare avanti solo di un nodo mentre `{b, c}` ci fanno andare avanti di due.

Nel caso fosse la seconda opzione, se troviamo due percorsi che portano a due nodi diversi seguendo lo stesso numero di elementi di `s`, quale dei due predilige?

Grazie

**Comment by nicolaprezza** [comment]
s va seguito sempre nell'ordine s[0], s[1], s[2], .... quindi la risposta giusta è la numero 1.

**Comment by depi-e** [comment]
Buongiorno avrei un dubbio al riguardo, essendo che s va sempre seguito nell'ordine s[0], s[1], .. , nel caso il cui s[0] non corrisponda a nessuna label, ma s[1] si,  quale è il corretto comportamento? 
1. Si restituisce la radice in quanto s[0] non corrisponde a nulla.
2. Oppure si ignora s[0] e si va avanti a cercare corrispondenze ordinate con s[1], s[2] ..

**Comment by jermp** [comment]
Comportamento num. 1.
