### ISSUE TITLE
File di sample errati commentati

### ISSUE THREAD

**Issue by kirpachov** [PEL-unive/progetto-23-24#2]
Salve buongiorno a tutti.
Cercando di descrivere la grammatica context-free necessaria allo svolgimento dell'esercizio, mi sono imbattuto in uno degli esempi "invalidi".

datasets/trie_char_error1.tr

Non riesco a capire perché questo esempio sarebbe invalido.
Ho cercato di disegnare l'albero corrispondente con il seguente risultato:

![IMG_20240508_081217](https://github.com/PEL-unive/progetto-23-24/assets/43368059/5f04aded-1801-4d81-a06d-18976b8733de)

Testo del file:
```
children = {
	a 3.1 children = {},
	b children = {
		b 2.9 children = {},
		c children = {
			b 7.0 children = {}
		}
  }
}
```

Potreste dirmi dove sbaglio?

Sarebbe fantastico avere un commento sul perché ciascun file non è valido, nei file invalidi.

Grazie mille
Oleksandr Kirpachov

**Comment by nicolaprezza** [comment]
Hai ragione, l'esempio è corretto. Ho sistemato introducendo un errore. I file di esempio sono molto piccoli e gli errori si trovano facilmente a mano, non servono commenti. 

Gli altri file dovrebbero essere a posto. Faccio presente che questi sono solo alcuni esempi di errori di formato e non rappresentano una lista completa di tutti gli errori di formato che dovete controllare.

**Comment by kirpachov** [comment]
Perfetto, grazie!
