### ISSUE TITLE
Operator== su sottotrie

### ISSUE THREAD

**Issue by Brugno04** [PEL-unive/progetto-23-24#20]
2 sottotrie sono uguali se peso e figli sono identici o devono avere anche la label verso il padre uguale?

**Comment by jermp** [comment]
Sì, due sottotrie sono uguali se peso e figli sono identici ma la label verso il padre potrebbe essere anche diversa.

**Comment by kappall** [comment]
Salve, a me non è tanto chiaro questo punto. Due sottotrie, che sono a loro volta trie, sono uguali se i figli sono identici o il peso è lo stesso. Ma i figli a loro volta sono sottotrie, questo significa che sono uguali se i loro figlii sono identici o hanno lo stesso peso. Ecco un esempio
![trie3](https://github.com/PEL-unive/progetto-23-24/assets/145616025/9cd8ebf8-0658-441f-9ec4-ee5e71113ce0)
![trie3 1](https://github.com/PEL-unive/progetto-23-24/assets/145616025/f3ab0bba-9332-4f34-b5a7-33d14ca14938)

Per la definizione di prima questi 2 trie sono uguali, ma non lo sono. Vorrei capire dove sbaglio.
Grazie
