### ISSUE TITLE
Chiarimento operator==

### ISSUE THREAD

**Issue by kappall** [PEL-unive/progetto-23-24#21]
Salve, a me non è tanto chiaro questo punto. Due sottotrie, che sono a loro volta trie, sono uguali se i figli sono identici o il peso è lo stesso. Ma i figli a loro volta sono sottotrie, questo significa che sono uguali se i loro figlii sono identici o hanno lo stesso peso. Ecco un esempio
![trie3](https://github.com/PEL-unive/progetto-23-24/assets/145616025/9cd8ebf8-0658-441f-9ec4-ee5e71113ce0)
![trie3 1](https://github.com/PEL-unive/progetto-23-24/assets/145616025/f3ab0bba-9332-4f34-b5a7-33d14ca14938)

Per la definizione di prima questi 2 trie sono uguali, ma non lo sono. Vorrei capire dove sbaglio.
Grazie

_Originally posted by @kappall in https://github.com/PEL-unive/progetto-23-24/issues/20#issuecomment-2169991648_

**Comment by jermp** [comment]
Ciao,
dipende da quale sottotrie stai considerando. I due trie in figura hanno dei sottotrie che sono identici. Per esempio,
`children = {  g++ 2.8 children = {}, javac 3.1 children = {} }`.

Quindi, se `t1` è il primo trie e `t2` è il secondo trie, allora `t1[{"compilers"}] == t2[{"lab1"}]` è vero; ma `t1 == t2` è falso perchè le etichette dei figli delle radici sono diverse. (In sostanza, due trie sono uguali se tutto è identico, a meno della etichetta sull'arco che entra nella radice, se presente.)

Spero sia chiaro adesso!
