### ISSUE TITLE
load two times

### ISSUE THREAD

**Issue by kirpachov** [PEL-unive/progetto-23-24#22]
Salve buoasera.
Scrivo per chiedere una correzzione: in una delle consegne parziali ho un test case che fallisce per quanto riguarda il parser.
Ma il test case si chiama "load two times".
Caricando due volte lo stesso trie però è corretto che si abbia un errore, perché le label si ripeteranno!
O sbaglio?
Questo è l'output che mi trae in confusione:
```
**** running test: test_parser ****

[doctest] doctest version is "2.4.11"
[doctest] run with "--help" for options
===============================================================================
../test/test_parser.cpp:132:
TEST CASE:  load two times

../test/test_parser.cpp:154: FATAL ERROR: REQUIRE( false ) is NOT correct!
  values: REQUIRE( false )
  logged: ERROR --> unexpected parser_exception thrown: tried to add twice key 

===============================================================================
[doctest] test cases: 12 | 11 passed | 1 failed | 0 skipped
[doctest] assertions: 12 | 11 passed | 1 failed |
[doctest] Status: FAILURE!
```

Grazie
Oleksandr Kirpachov

**Comment by jermp** [comment]
Ciao,
no, come per un built-in type, se esegui:

    int x = 0;
    is1 >> x;
    is2 >> x;
    
allora `x` sarà uguale all'ultimo valore letto e non ad una "combinazione" dei due valori letti. Quindi, allo stesso modo, se fai

    trie<int> t;
    is1 >> t;
    is2 >> t;

`t` conterrà il trie parsato da `is2`. Se `t` è non vuoto, il suo contenuto verrà correttamente sovrascritto.

**Comment by kirpachov** [comment]
Indiscutibilmente giusto.

Grazie mille
Sasha
