### ISSUE TITLE
Dubbio su path_compress()

### ISSUE THREAD

**Issue by kappall** [PEL-unive/progetto-23-24#23]
Salve, volevo chiedere come dovevamo comportarci nel caso avessimo un trie<char> come figura 1:
![trie1](https://github.com/PEL-unive/progetto-23-24/assets/145616025/6ad1fc80-e755-495a-9433-e28177d1b1d9)
Qui la compattazione dovrebbe restituire al posto del nodo c una foglia con peso 7.0, ma per quanto riguarda la label? 
Sommando i caratteri ottengo un carattere non alfa-numerico, in questo caso ottengo '\xc5'.
Dobbiamo aspettarci che la compattazione non si farà per il tipo char, o dobbiamo trasformare la label in un altro modo?

Grazie
EK

**Comment by jermp** [comment]
> Qui la compattazione dovrebbe restituire al posto del nodo c una foglia con peso 7.0, ma per quanto riguarda la label?
Sommando i caratteri ottengo un carattere non alfa-numerico, in questo caso ottengo '\xc5'.

Tutto corretto. Il fatto che tu ottenga un carattere non alfa-numerico o che tu abbia un overflow, non importa. Stai usando `operator+` definito su char (che è un signed int), quindi è tutto corretto.
