### ISSUE TITLE
dubbio sul comportamento di path_compress()

### ISSUE THREAD

**Issue by Naccaa** [PEL-unive/progetto-23-24#24]
Buon giorno, 

Se io chiamo path_compress() sul trie parametrizzato con interi “children = { 7 9 children={}}” quale comportamento devo aspettarmi dal metodo? 
1) Non viene applicata nessuna compressione poiché root non può aver una label 
2) Restituirà “9 children = {}” dove la compressione è avvenuta eliminando la label (sempre perhé root non deve avere label) e “spostando” il peso correttamente 
3) Restituirà “7 9 children={}” attribuendo una label a root 

La ringrazio in anticipo

**Comment by jermp** [comment]
Ciao,
dovresti aspettarti il comportamento 1. Vedi anche la seguente issue: https://github.com/PEL-unive/progetto-23-24/issues/18.
