### ISSUE TITLE
Sintassi costruttore del file list.cpp

### ISSUE THREAD

**Issue by 900869** [PEL-unive/progetto-23-24#25]
Salve, non mi è ben chiara la sintassi con con cui è stato scritto il costruttore del container list nel file list.cpp:

```
template<typename Val>
list<Val>::list() : m_front(nullptr), m_back(nullptr) {}
```

**Comment by jermp** [comment]
Ciao, questa non è una domanda pertinente al progetto, dato che non c'è nessun file `list.cpp` in questo repository (e non deve esserne consegnato alcuno).

La sintassi è stata spiegata a lezione: è una forma alternativa che usa i costruttori dei dati membro, invece che il semplice assegnamento. In questo caso, tuttavia, l'assegnamento è efficiente quanto il costruttore dato che vengono copiati dei puntatori.
