### ISSUE TITLE
Iteratori su sotto-trie

### ISSUE THREAD

**Issue by RicuxUni** [PEL-unive/progetto-23-24#26]
Nella sezione 3.7 leggo quanto sotto riportato

> IMPORTANTE Gli iteratori devono funzionare in modo consistente anche su sotto-tries.
> ....omissis...
>  In altre parole, il for loop del codice sopra deve correttamente navigare solo due foglie e stampare b b. 
> 

Per fare questo avrei la necessita' di salvare all'interno dell'iteratore la radice del trie di partenza (dato che m_ptr punta di volta in volta alla foglia corrente).
Ma la consegna dice che non possiamo aggiungere nulla al file trie.hpp.
Potrei rispettare formalmente la consegna faccendo cose strane sulla classe bag, cioe' facendo in modo che m_ptr punti ad un oggetto trie fittizio che ha un bag con le informazioni che mi servono (foglia corrente e radice) per iterare sulle foglie corrette. Questo pero', credo, andra' oltre lo spirito del progetto.

**Comment by nicolaprezza** [comment]
No, non ti serve la radice del trie di partenza. La classe iterator contiene già tutto quello di cui hai bisogno per risolvere l'esercizio.

Nota che operator++ di leaf_iterator deve solo preoccuparsi di raggiungere la foglia successiva, indipendentemente dal trie/sotto-trie al quale questa foglia appartiene. Eventuali controlli sulla fine della catena di foglie (for loop dell'esempio che citi) vengono fatti fuori da leaf_iterator, dove conosci la radice del sotto-trie sul quale stai iterando.
