### ISSUE TITLE
Chiarimento copy constructor

### ISSUE THREAD

**Issue by xjaki21** [PEL-unive/progetto-23-24#27]
Salve, non mi è ben chiaro come ci si bisogna comportare nel caso venga copiata una foglia, quindi di un trie senza figli ma con solo il peso(ed eventualmente la label). Viene copiato il peso della foglia in questione o non è necessario?
Per esempio un trie di questo genere (descritto come valido):
trie<int> t1(3.2);
trie<int> t2=t1;

I due trie avranno peso uguale?

**Comment by jermp** [comment]
Sì, i due trie (entrambi foglie) avranno lo stesso peso.
