### ISSUE TITLE
copy/move semantics

### ISSUE THREAD

**Issue by kirpachov** [PEL-unive/progetto-23-24#28]
Salve una domanda veloce.
Quando copio un trie, devo copiare anche m_p giusto?

Grazie
Oleksandr Kirpachov

**Comment by jermp** [comment]
Mmh non direi: pensa al caso in cui vuoi copiare un sotto-trie in un altro.
Ad esempio, se S è un sotto-trie di T, e fai S = S', dove S' è un altro trie.
È corretto che il sotto-trie S mantenga il proprio padre (cioè, rimanga un sotto-trie di T).

**Comment by kirpachov** [comment]
Certo e nel caso in cui si tratti di due sotto-trie ha perfettamente senso.
Ma se creo un nuovo trie copiando un sotto-trie?
L'associazione con il padre si copia?
```cpp
int main() {
  trie<char> t = make_trie("children = { a children = { b 3.9 children = {} } }");
  trie<char> a_copy = t[std::vector<char>{'a'}];
  // a_copy.m_p == &t // <-- questo è il dubbio
}
```

Per come me l'ero immaginato io, se il lhs non ha un padre gli assegno il padre del rhs, quindi la comparazione commentata darebbe true nel mio caso.
È sbagliato?

Grazie
Oleksandr Kirpachov

**Comment by jermp** [comment]
Se copi da un sotto-trie, non devi comunque copiare il suo padre, altrimenti staresti effettivamente copiano di "più".
Infatti la copia deve essere del tutto indipendente dal sotto-trie che viene copiato.

**Comment by kirpachov** [comment]
Ah okay, aggiorno subito il codice di conseguenza

Grazie mille
Oleksandr Kirpachov
