### ISSUE TITLE
radice del sotto-trie

### ISSUE THREAD

**Issue by kirpachov** [PEL-unive/progetto-23-24#29]
Salve, nella documentazione c'è un paragrafo che recita
```md
Importante: Gli iteratori devono funzionare in modo consistente anche su sotto-tries. Per far ciò, è essenziale fornire un'accurata implementazione dei metodi root(), begin() e end() di trie<T>. Infatti, notare che su un sotto-trie, tali metodi restituiranno iteratori alla radice/prima foglia/foglia successiva all'ultima foglia del sotto-trie che non necessariamente coincidono con la radice/prima foglia/foglia successiva all'ultima foglia del trie dal quale è stato istanziato il sotto-trie. Per esempio, considerate il trie di Figura 1. Chiamiamo questo trie t. Su questo trie, t.begin() è quindi un leaf_iterator alla foglia di peso 3.1, mentre t.end() è un leaf_iterator alla posizione successiva alla foglia di peso 7.0. Considerate ora il trie t2 costruito come segue:
```

La ::root() di un sotto-trie coincide sempre con la root() del trie originale però, perché per definizione la radice è l'unico trie senza padre, è corretto?

Grazie
Oleksandr Kirpachov

**Comment by nicolaprezza** [comment]
No: la radice del sotto-trie **t** è **t** stesso. La definizione di "radice" all'inizio del documento si applica solo ai trie (non sotto-trie). In generale, se **t** è un trie o sotto-trie, **t.root()** restituisce un iteratore a **t**. Ho aggiunto una nota nella documentazione.
