### ISSUE TITLE
Caso particolare Unione

### ISSUE THREAD

**Issue by kappall** [PEL-unive/progetto-23-24#30]
Salve ho un dubbio sull'unione dei trie, nel caso uno dei 2 sia una foglia. Per esempio, siano a, b, c trie<char> tali che c = a + b.
```
a:
3.1 children = {}

b:
children = {
  x 2.2 children = {}
}
```
mi vengono in mente 2 possibili risultati:
```
c:
1) (somma dei pesi)
children = {
  x 5.3 children = {}
}
2) (rimane b invariato)
children = {
  x 2.2 children = {}
}
```

Quale è quello giusto?

**Comment by nicolaprezza** [comment]
il trie 'a' codifica un insieme che contiene una sequenza vuota di peso 3.1. La sequenza vuota è un prefisso della sequenza "x" contenuta nel trie 'b', quindi si applica la regola generale di sezione 3.9 e il risultato corretto è 1).
