### ISSUE TITLE
Chiarimento sul parser

### ISSUE THREAD

**Issue by xjaki21** [PEL-unive/progetto-23-24#31]
Salve, un file '.tr' di questo tipo:
children={
   achildren={
           s1.1 children={}
    }
}
è valido se è di tipo trie<char>? O bisogna che ci sia uno spazio tra la 'a' e 'children'? (Stesso dubbio per 's' e '1.1').
Nel caso fosse un trie<string> bisogna comportarci allo stesso modo?

**Comment by nicolaprezza** [comment]
Sì, chiaramente ci devono essere spazi tra 'a' e 'children' e tra 's' e '1.1'.
