### ISSUE TITLE
Move Constructor

### ISSUE THREAD

**Issue by kappall** [PEL-unive/progetto-23-24#32]
Salve, vorrei chiedere se il move constructor dovesse comportarsi come il move assignment, cioè : "rubare" solo figli(m_c) o copiare il peso(m_w) se fosse una foglia; oppure si dovesse "rubare" anche la label.

Grazie
EK

**Comment by nicolaprezza** [comment]
Sì, come al solito move assignment/constructor hanno la stessa semantica.
