### ISSUE TITLE
Dubbio sull'implementazione dei label

### ISSUE THREAD

**Issue by bonorariccardo892867** [PEL-unive/progetto-23-24#33]
Nell'header di trie.h, sulla sezione private, il dato che rappresenta i label viene richiesto che sia salvato come puntatore. Da quanto sono riuscito a capire il label ci serve per identificare l'arco che collega un nodo trie a un'altro. Non capisco perché questo dato sia un puntatore.

**Comment by nicolaprezza** [comment]
Perchè non è sempre necessario (per esempio, radice).
