### ISSUE TITLE
Problema scorrimento del node_iterator

### ISSUE THREAD

**Issue by bonorariccardo892867** [PEL-unive/progetto-23-24#34]
Ho un dubbio sul funzionamento del node_iterator. se non ci è possibile implementare un metodo che fornisce l'inizio dell'iteratore come possiamo scorrere gli elementi dell'iteratore dal nodo di riferimento al root?

**Comment by nicolaprezza** [comment]
Il metodo c'è: è il metodo operator node_iterator(); di leaf_iterator. C'è pure [un esempio](https://github.com/PEL-unive/progetto-23-24/blob/fbf7257c528650ec7bbdeb756db71e3648d339c0/README.md?plain=1#L360) nella specifica di progetto.
