### ISSUE TITLE
Domande sul parser e su bag

### ISSUE THREAD

**Issue by Pingu-Io** [PEL-unive/progetto-23-24#35]
Salve, volevo fare alcune domande.

Supponendo di avere un file .tr come segue:
```
children = {
    a 1.1 children = {
        b 4.4 children = {}
    },
    x 5.5 children = {}
}
```
Si può notare che il nodo con arco 'a' ha un peso di troppo che non dovrebbe esserci in quanto non è una foglia perchè presenta un figlio. In questo caso il formato è da considerarsi non valido e throware un eccezione o tentare di risolvere il problema rimuovendo il peso dal nodo e quindi non considerandolo più come foglia?

Un altra domanda riguarda bag, volevo chiedere se sia "legale" chiamare metodi di trie all'interno della bag, ho letto altre issue che intendo che si possa fare, il problema è che in questo modo si andrebbe a perdere la genericità di bag.

Un altra domanda riguarda i label, c'è un limite di caratteri per quanto riguarda i label? Se sono troppo lunghi è legittimo che il parser dia errore o bisogna prevedere che abbiano una lunghezza "illimitata"?

**Comment by jermp** [comment]
Ciao,

> Si può notare che il nodo con arco 'a' ha un peso di troppo che non dovrebbe esserci in quanto non è una foglia perchè presenta un figlio. In questo caso il formato è da considerarsi non valido e throware un eccezione o tentare di risolvere il problema rimuovendo il peso dal nodo e quindi non considerandolo più come foglia?

Lanciare un'eccezione è corretto in questo caso perché solo le foglie hanno un peso.

> Un altra domanda riguarda bag, volevo chiedere se sia "legale" chiamare metodi di trie all'interno della bag, ho letto altre issue che intendo che si possa fare, il problema è che in questo modo si andrebbe a perdere la genericità di bag.

Sì, puoi farlo assumendo che il tipo `T` abbia in metodi di `trie`.

> Un altra domanda riguarda i label, c'è un limite di caratteri per quanto riguarda i label? Se sono troppo lunghi è legittimo che il parser dia errore o bisogna prevedere che abbiano una lunghezza "illimitata"?

Non ci sono limiti. Anche perché quello che chiedi si applicherebbe soltanto al caso in cui il tipo `T` sia `std::string`. Attenzione che `T` può essere qualsiasi tipo provvisto con le operazioni descritte nella specifica (quindi, può essere `char`, `int`, `double`, etc.), non necessariamente una stringa.
