### ISSUE TITLE
Condizioni peso

### ISSUE THREAD

**Issue by ilovecodingtoo** [PEL-unive/progetto-23-24#36]
Salve, volevo chiedere cortesemente se per il peso delle foglie ci fosse qualche sorta di condizione o limite, come, per esempio, il fatto che debba essere strettamente positivo e che solo per i nodi interni possa essere uguale a 0.0, come da inizializzazione. Ringrazio in anticipo per la risposta,
Lago

**Comment by jermp** [comment]
Ciao,
no, non c'è nessuna restrizione specifica: il peso può essere anche negativo e posso esistere foglie con peso 0.
-Giulio
