### ISSUE TITLE
Tipo T e string

### ISSUE THREAD

**Issue by LucaAdolfo** [PEL-unive/progetto-23-24#37]
Salve, ho dei dubbi che volevo chiarire con queste domande

1. Approposito di come definite il tipo T, per fare il parser basta basarsi sui tipo primitivi come int, double, char e per esempio anche string? 

2. La libreria string è inclusa negli include da voi forniti?

3. Per aiutarmi a fare il parser posso creare funzioni di supporto in trie.cpp?

Grazie in anticipo.

**Comment by jermp** [comment]
Ciao.

1. No. Il tipo `T` è generico e non necessariamente un tipo primitivo. Quello che deve soddisfare `T` è descritto nella specifica, all'inizio di Sez. 2:

        Il tipo T deve soddisfare i seguenti requisiti affinchè trie<T> sia ben definito:
        
        Il tipo T deve definire operator<, operator==, operator<<, e operator>>. Per l'operazione in Sezione 3.9.2. (facoltativa), si richiede anche operator+.
        Gli oggetti di tipo T, quando scritti su un std::ostream (tramite operator<<), non devono contenere separatori (spazi, tab, newline, etc.).

2. Tipicamente `string` è direttamente inclusa da `iostream`. Detto ciò, non ti servono altre direttive include oltre a quelle fornite e non puoi usarne altre.

3. Certamente!

-Giulio
