### ISSUE TITLE
Caso base file vuoto

### ISSUE THREAD

**Issue by ilovecodingtoo** [PEL-unive/progetto-23-24#38]
Buongiorno, volevo chiedere a proposito di un dubbio su uno dei casi base, ovvero: nella circostanza in cui dovessimo codificare un file vuoto, ci ritroveremmo nella funzione che fa l'overloading dell'operatore >> con una reference al trie da sviluppare tra i parametri, il che comporta che sia stato chiamato il costruttore di default di quest'ultimo prima del passaggio come argomento, inizializzando i vari campi a nullptr e il peso a 0.0, ma allora come faremmo a distinguere in output un trie vuoto da un ipotetico trie costituito da una singola foglia di peso 0? Non sarebbe forse più corretto che anche il campo m_w fosse un puntatore in modo da poterlo inizializzare a nullptr? Oppure permettere di includere la libreria <limits> e nel caso inizializzare m_w a infinito? Spero di essermi espresso in modo chiaro e ringrazio in anticipo per la risposta.

**Comment by jermp** [comment]
Ciao,
sì, hai ragione. Il costruttore di default crea sempre un foglia di peso 0, quindi effettivamente non abbiamo mai un trie "vuoto". Il caso di file vuoto menzionato nella specifica è una svista (ho aggiornato il README): assumete pure che i tests saranno sempre fatti su file non vuoti.

Buon lavoro,
-Giulio
