### ISSUE TITLE
Dubbio su un caso base

### ISSUE THREAD

**Issue by Callistri** [PEL-unive/progetto-23-24#39]
Buongiorno, volevo chiedervi se questo può essere considerato un caso base:
a 17.5 children={}
che andrebbe a creare un trie di questo tipo:
![caso base](https://github.com/user-attachments/assets/8b6111e9-44c4-4657-a175-8a4f434b77d4)
O se questo può essere creato solo se il file è scritto così:
children={
   a 17.5 children={}
}

Grazie in anticipo!

**Comment by jermp** [comment]
Ciao,
il file corrispondente al trie in figura è il secondo che hai scritto, cioè 

    children = {
         a 17.5 children = { }
    }

infatti esso ha due nodi. Invece, il file

    a 17.5 children ={ }

ha un solo nodo (una foglia di peso 17.5).

**Comment by Callistri** [comment]
Ma quindi se leggo il file composto unicamente da 
a 17.5 children ={ }
vado a ignorare la label o lancio un'eccezione?

**Comment by jermp** [comment]
Devi lanciare un'eccezione: una label è associata ad un arco che connette *due* nodi, ma in questo caso ne hai solo uno.

**Comment by Callistri** [comment]
Perfetto, grazie del chiarimento!
