### ISSUE TITLE
Implementazione operatori di assegnamento

### ISSUE THREAD

**Issue by Brugno04** [PEL-unive/progetto-23-24#4]
Salve, ho dei dubbi sul da farsi in diverse situazioni di assegnamento:

![esempio](https://github.com/PEL-unive/progetto-23-24/assets/161490108/68909f08-fdb0-4e37-a3fe-f41799445e98)

Ad esempio in questo caso vanno copiati dal secondo albero solo i figli del nodo evidenziato o anche la label e il genitore, andando così a perdere il resto del primo albero per farlo diventare uguale al secondo?

La stessa domanda nel caso copiassi la radice del secondo albero sempre nella foglia a,1. In questo caso, essendo la radice del secondo albero senza genitori, copiandola totalmente nel nodo a,1 andrei a perdere tutto il resto dell'albero, è giusto fare così?

Grazie mille,
Davide Brugnotto

**Comment by jermp** [comment]
Ciao,

nell'esempio in figura, l'intero sotto-trie radicato nel nodo interno evidenziato in arancione andrà a "rimpiazzare" la foglia del primo trie, i.e. la foglia diventa il sotto trie di destra, quindi ottenendo un trie corrispondente alle sequenze `{ (ae,4) (af,5) (b,2) }`.

Nel secondo caso, vale lo stesso: l'intero albero di destra viene copiato nella foglia, quindi ottenendo le sequenze `{ (ac,3) (ade,4) (adf,5) (b,2) }`.

-Giulio
