### ISSUE TITLE
Sequenza nodi di leaf iterator 

### ISSUE THREAD

**Issue by RicuxUni** [PEL-unive/progetto-23-24#41]
Salve, ho un dubbio sul ordine di nodi restituiti dal leaf iterator
Nel trie 
![Screenshot 2024-09-10 170732](https://github.com/user-attachments/assets/a8ac3171-c4ff-4f11-8344-4d3db991473b)
i figli di ogni nodo sono ordinati lessicograficamente, ma se si scorrono i nodi da sinistra a destra (come avevo inizialmente capito) ottengo 
b associato alla sequenza  (a, b)
c associato alla sequenza (a, c)
abc associato alla sequenza (abc)

Questo però non è in ordine lessicografico come richiesto nelle specifiche.

Si vuole davvero che vengano restituiti nell'ordine seguente?
b associato alla sequenza  (a, b)
abc associato alla sequenza (abc)
c associato alla sequenza (a, c)

Per fare questo non occorrerebbe conservare altre informazioni nell'iteratore?

**Comment by nicolaprezza** [comment]
Buongiorno, 

L'ordine corretto delle foglie è il primo:

foglia associata alla sequenza (a, b)
foglia associata alla sequenza (a, c)
foglia associata alla sequenza (abc)

Il punto è che questo è un trie di std:string, non di char. L'ordine lessicografico quindi non è su sequenze di char (concatenazione delle stringhe come dici), ma su sequenze di stringhe: ["a","b"] < ["a","c"] < ["abc"]. L'ordine su stringhe viene usato solo per comparare le coppie di elementi di queste sequenze di stringhe.

Nicola
