### ISSUE TITLE
Chiarimento riguardo il parser: foglie

### ISSUE THREAD

**Issue by pietrozanasi** [PEL-unive/progetto-23-24#42]
Una domanda molto semplice: sono consentiti spazi fra le parentesi graffe al livello foglia?
Per esempio: "0.4 children = {   }" è un formato valido?
Grazie,
Pietro Zanasi

**Comment by jermp** [comment]
Ciao,
sì certamente. Il parser deve funzionare correttamente anche in presenza di un numero
qualsiasi di caratteri invisibili.
