### ISSUE TITLE
Caratteri invisibili

### ISSUE THREAD

**Issue by LucaAdolfo** [PEL-unive/progetto-23-24#43]
Buongiorno, ho letto dal precedente issue che il parser deve funzionare anche in presenza di caratteri invisibili. Ma possono essere presenti in qualsiasi parte che stiamo parsando? per esempio potrebbe essere sia nella parola children oppure magari dentro il double? e in tutti questi casi i caratteri invisibile andrebbero ignorati oppure si dovrebbe lanciare una parser exception? e se il trie fosse di tipo string, con  il carattere invisibil dentro la label, la label del trie dovrebbe contenerlo o no? 
Scusi il disturbo,
Distinti saluti,
Luca Adolfo

**Comment by jermp** [comment]
Ciao,
i caratteri invisibili posso essere dovunque tranne che "in mezzo" a labels, pesi, e la parola chiave "children".
Se ci sono in tali casi, allora un'eccezione andrebbe lanciata.
Vedi anche questa issue precedente: https://github.com/PEL-unive/progetto-23-24/issues/31.

Ad esempio, con il seguente file:

```
chi
  ldren = {

}
```

che corrisponde ad un errore di sintassi, il parser deve lanciare un'eccezione.
Stessa cosa con, assumendo un `trie<std::string>`:

```
children = {
   giu  lio 3. 8973 children = { }
}
```

Invece, il seguente file è ammissibile:

```
    children 

=       {  giulio    3.8973

children = {

}
}
```
