### ISSUE TITLE
Operatori di assegnamento

### ISSUE THREAD

**Issue by nena-21** [PEL-unive/progetto-23-24#44]
![pergithub](https://github.com/user-attachments/assets/fa5c7bbd-4b47-4602-a65e-ee391bee590b)
Salve, avrei qualche domanda sul funzionamento degli operatori di assegnamento.
Se volessi assegnare a questo nodo in foto tutto l'albero, i figli del nodo alla sinistra dell'uguale andrebbero persi? E quindi anche distrutti? Oppure i nodi (g,h) devono essere aggiunti come fratelli di (a,b)?

**Comment by jermp** [comment]
L'intero sottoalbero radicato nel nodo evidenziato in rosso a sinistra verrà rimpiazzato dal sottoalbero radicato nel nodo evidenziato in rosso di destra. Quindi il sottoalbero di sinistra verrà eliminato (memoria liberata), mentre non succede niente al sottoalbero di destra.
