### ISSUE TITLE
move semantics

### ISSUE THREAD

**Issue by LucaAdolfo** [PEL-unive/progetto-23-24#45]
Buonasera,

Vorrei chiedere alcune informazioni sul comportamento dell'operatore move quando viene utilizzato tra un nodo di un trie e la sua radice (o, in generale, qualsiasi nodo che si trovi più in alto nel percorso tra la radice e il nodo).

Come dovrebbe reagire il codice a questa azione? Dovrebbe essere lanciata un'eccezione quando il lato destro dell'operazione di move condivide la stessa radice del lato sinistro, oppure questa operazione dovrebbe essere consentita?
Ad esempio:
```
trie<string>& figlio1 = *(radice.get_children()[0]); //prende il figlio in posizione 0
    figlio1 = std::move(radice);
    //oppure
    radice = std::move(figlio1)
```

**Comment by jermp** [comment]
Ciao,
questi due scenari non hanno senso. Per esempio in `figlio1 = std::move(radice);` la memoria di `figlio1` verrebbe liberata per poi essere sostituita dall'albero radicato in `radice` che però comprende comunque `figlio1`. Stesso discorso per `radice = std::move(figlio1)`: prima dovresti liberare tutta la memoria per il trie radicato in `radice` per poi rubare la memoria da `figlio1` che però non ha più memoria.

Questi casi non sono presenti nei test.
