### ISSUE TITLE
Load, save, reload and compare

### ISSUE THREAD

**Issue by sharpine** [PEL-unive/progetto-23-24#46]
Salve, 
scrivo per chiedere delucidazioni riguardo il seguente test case

> ../test/test_parser.cpp:102:
TEST CASE:  load, save, re-load with our code and compare
../test/test_parser.cpp:102: ERROR: test case THREW exception: unknown exception

Non mi è chiara la natura di tale eccezione e quale sarebbe il comportamento atteso dal codice

**Comment by jermp** [comment]
Ciao,
questo significa che il tuo codice lancia una eccezione quando non dovrebbe.
