### ISSUE TITLE
Definizione nodo padre/figlio

### ISSUE THREAD

**Issue by derenda-stud** [PEL-unive/progetto-23-24#5]
Dalla descrizione risulta che "17.5 children = {}" è un formato valido di file.
Interpretando il trie come nodo foglia il grafico corrispondente è quello in figura A, dove il nodo coincide anche alla radice.

Mi chiedevo: E' possibile chiamare il metodo "add_child()" su questo nodo?
In questo caso il nodo associato diverrebbe un padre, invalidando quindi il peso memorizzato [Figura B]?

![nodo](https://github.com/PEL-unive/progetto-23-24/assets/148547670/6d200703-57c4-40cc-9ea9-d0d96235a1ea)

**Comment by nicolaprezza** [comment]
Hai ragione, non abbiamo specificato questo dettaglio. Il punto è che add_child è una funzione di supporto per il parser, quindi la situazione B non si verifica mai. Aggiungo un commento al README: il comportamento di add_child non è definito quando questa funzione viene chiamata su una foglia (in altre parole non genereremo mai questa situazione in fase di testing).

**Comment by nicolaprezza** [comment]
Giusta osservazione: dato che i costruttori di trie (a parte copy/move) costruiscono foglie, add_child su una foglia deve agire come nel caso B da te illustrato. Ho aggiornato il readme. Grazie per la segnalazione!
