### ISSUE TITLE
Mancanza operatore minore

### ISSUE THREAD

**Issue by giacomoBaratto** [PEL-unive/progetto-23-24#6]
Salve,
leggendo la sezione 2 c'è scritto che T deve definire l'operatore < e dato che il container bag definisce un bag<T> e non di tipo bag<Trie<T>>, non è possibile accedere alla label per la comparazione durante inserimento.
Inoltre leggendo la sezione 3, nel primo paragrafo si legge che " il container bag, che mantiene l'insieme dei nodi figli ordinati per etichetta crescente (usando opportunatamente operator< definito su T) ", dunque dal punto di vista di bag, trie<T> è il T, e quindi trie dovrebbe implementare operator<, ma non essendone presente la firma nel file trie.hpp, ne suggerisco l'aggiunta.

Cordiali saluti
Baratto Giacomo

**Comment by nicolaprezza** [comment]
Buongiorno, 

Non serve: dentro l'oggetto bag puoi chiamare get_label() sui trie da comparare. Semplicemente, l'istanziazione template di bag< Val > funzionerà solo quando Val definisce una funzione get_label() che restituisce un tipo T che definisce operatore< (come nel nostro caso).

In ogni caso, se ti piace di più la soluzione che menzioni tu (più generale, dato che poi bag potrà essere usato su qualsiasi Val che definisce operator<), puoi sempre definire questo operatore come non-membro di trie.
