### ISSUE TITLE
Metodo end() e unicità sottoalberi

### ISSUE THREAD

**Issue by LucaBiscotti** [PEL-unive/progetto-23-24#7]
Ho due domande per due argomenti distinti:

1. Viene specificato più volte che il metodo end() debba restituire un leaf_iterator alla foglia successiva all'ultima, ma fatico a capire a cosa si fa riferimento. Come fa ad esistere una foglia successiva all'ultima foglia, se difatti questa è l'ultima. Possibile che si debba restituire sempre e solo una foglia vuota?
2. Inizialmente ha specificato che un nodo non può avere figli uguali, quindi tutti i sottoalberi fratelli devono essere distinti, ma questo vale anche a livello globale? Mi spiego meglio:
se io dovessi avere la seguente struttura:
```
children = {
      a children = {b children = {c 2.0 children = {} } },
      c 2.0 children = {}                                //qua istanzio parte del sottoalbero del primo figlio
}
```

Nell'esempio, i due figli della radice sono diversi, seppure in realtà, parte del sottoalbero del primo figlio (c) è identico al secondo figlio della radice.
In questo caso il file è in un formato valido? E quindi, possono esserci ripetizioni di sottoalberi all'interno di tutto l'albero?

**Comment by nicolaprezza** [comment]
1. Stessa logica del container list< Val > visto a lezione: anche in quel caso, end() restituisce un iteratore che punta alla cella successiva all'ultima. Controlla cosa abbiamo fatto in quel caso. 
2. Leggi bene la specifica: ad essere distinte devono essere le etichette, non i sotto-alberi: https://github.com/PEL-unive/progetto-23-24/blob/bd8545f54cd191f098035031b956e156902fda4a/README.md?plain=1#L67
