### ISSUE TITLE
Gestione delle eccezioni dentro bag

### ISSUE THREAD

**Issue by derenda-stud** [PEL-unive/progetto-23-24#8]
Durante l'esecuzione del parser bisogna controllare che l'etichetta del nodo da inserire non sia già presente tra i figli.

Sarebbe corretto lanciare l'eccezione all'interno della classe bag, nonostante non abbia accesso a `parser_exception`? (In questo caso si potrebbe richiamare una `assert` oppure un'eccezione contenuta nella libreria `iostream`)

Oppure dovremmo delegare la gestione dell'eccezione alla classe trie, direttamente nel metodo `add_child`?

**Comment by nicolaprezza** [comment]
Questa cosa andrebbe verificata dentro alle funzioni del parser (in trie.cpp). Non lanciate eccezioni che non siano parser_exception.
