### ISSUE TITLE
Const Correctness nel leaf_iterator e max()

### ISSUE THREAD

**Issue by mattiacerutti** [PEL-unive/progetto-23-24#9]
Implementando il metodo `max()`, mi sono trovato a voler usare il `leaf_iterator` precedentemente implementato in modo da semplificare l'algoritmo. 

Mi sono imbattuto però in una questione che non capisco se sia voluta (il che quindi mi vieta di utilizzare il leaf_iterator in questo caso, nonostante sarebbe il suo esatto scopo) o meno: la funzione max ritorna una reference a `trie<T>` **non-const**, il che lascia quindi intendere che si possa poi modificare a piacimento la trie ritornata, ma la funzione `get_leaf()` (sia del `leaf_iterator` che del `const_leaf_iterator`) ritorna una **const** reference a trie, rendendo impraticabile l'uso dell'iteratore. 

E' normale e voluto che anche il leaf_iterator non const ritorni una reference const?

**Comment by jermp** [comment]
Ciao,
hai ragione: il metodo `get_leaf` di `leaf_iterator` è giusto che ritorni una reference (e non `const&`), così da porter usare il `leaf_iterator` per l'implementazione di `max()`. Modifico il file `trie.hpp` di conseguenza.

Grazie!
